title: "Jahanara Suchi"
name: "Jahanara Suchi"
description: "PhD Applicant | Computer Science | Machine Learning | Artificial Intelligence"
url: "https://jahanra02.github.io"
repository: "jahanra02/jahanra02.github.io"

author:
  name: "Jahanara Suchi"
  avatar: "new.png"
  bio: "PhD applicant interested in Machine Learning, Deep Learning, Explainable AI, and Healthcare AI."
  location: "Dhaka, Bangladesh"
  employer: "Independent Researcher"
  email: "jahanara.suchi41985@gmail.com"
  googlescholar: ""
  orcid: ""
  linkedin: "jahanara-suchi-218b78208"
  github: "jahanra02"
